delete_table:
	bash bash/delete_table.sh
create_table:
	bash bash/create_table.sh
write_data:
	bash bash/write_data.sh
get_data:
	bash bash/get_data.sh
table_status:
	bash bash/table_status.sh
point_recovery:
	bash bash/point-in-time-recovery.sh


